### PR TITLE
remove useless log

### PR DESCRIPTION
**Pull request by jjsaunier**
Let's the application level warn about auth user, this layer is used on every request and polluate the log file for nothing, there is no value to log that

### CODE REVIEW

**Comment by remi-san** [comment]
I don't think this log call is the problem.
In fact, I think the opposite way: I think the problem is the level of what we log in the polluted file.
Strongly against this PR

**Comment by SelrahcD** [comment]
I disagree.
The issue is that now everything is logged in the same place, which was not the case before, and a log file for this purpose was created.
In my opinion you have 2 choice :

**Comment by ProPheT777** [comment]
```
[2016-02-25 15:00:04] app.request.NOTICE: Route rest-get-all.fr matched [] {"url":"/api/v2/cotcot","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":null,"tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"12 MB"}
[2016-02-25 15:00:05] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/cotcot","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/cotcot","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":null,"tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"15 MB"}
[2016-02-25 15:00:08] app.request.NOTICE: Route rest-get-all.fr matched [] {"url":"/api/v2/cotcot","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"14.25 MB"}
[2016-02-25 15:00:08] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/cotcot","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/cotcot","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"22.5 MB"}
[2016-02-25 15:00:10] app.request.NOTICE: Route rest-get-one.fr matched [] {"url":"/api/v2/quotes/803841?embed=messages.userFrom,messages.attachments.file,messages.metadata,site.language,localAgency,localAgency.siteDetails,metadata,traveller.quotes.site,traveller.quotes.testimonial,localAgent.user,users,attachments,quote_extended,billLines.bill,proformaLines,itinerary,phonecalls,phonecalls.quotesHasPhonecalls,drafts,labels","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"13.5 MB"}
[2016-02-25 15:00:10] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/quotes/803841?embed=messages.userFrom%2Cmessages.attachments.file%2Cmessages.metadata%2Csite.language%2ClocalAgency%2ClocalAgency.siteDetails%2Cmetadata%2Ctraveller.quotes.site%2Ctraveller.quotes.testimonial%2ClocalAgent.user%2Cusers%2Cattachments%2Cquote_extended%2CbillLines.bill%2CproformaLines%2Citinerary%2Cphonecalls%2Cphonecalls.quotesHasPhonecalls%2Cdrafts%2Clabels","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/quotes/803841?embed=messages.userFrom,messages.attachments.file,messages.metadata,site.language,localAgency,localAgency.siteDetails,metadata,traveller.quotes.site,traveller.quotes.testimonial,localAgent.user,users,attachments,quote_extended,billLines.bill,proformaLines,itinerary,phonecalls,phonecalls.quotesHasPhonecalls,drafts,labels","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"18.75 MB"}
[2016-02-25 15:00:14] app.request.NOTICE: Route message-drafts-get-all.fr matched [] {"url":"/api/v2/messageDrafts?author.id=293298&number=1&quote.id=803841","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"13.25 MB"}
[2016-02-25 15:00:14] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/messageDrafts?author.id=293298&number=1&quote.id=803841","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/messageDrafts?author.id=293298&number=1&quote.id=803841","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"21.25 MB"}
[2016-02-25 15:00:15] app.request.NOTICE: Route rest-get-all.fr matched [] {"url":"/api/v2/currencyrates?currency.id=4&number=1","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"15.75 MB"}
[2016-02-25 15:00:15] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/currencyrates?currency.id=4&number=1","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/currencyrates?currency.id=4&number=1","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"24 MB"}
[2016-02-25 15:00:16] app.request.NOTICE: Route label-get-all.fr matched [] {"url":"/api/v2/labels?page=1","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"10.5 MB"}
[2016-02-25 15:00:16] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/labels?page=1","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/labels?page=1","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"13.5 MB"}
[2016-02-25 15:00:17] app.request.NOTICE: Route label-get-all.fr matched [] {"url":"/api/v2/labels?page=1","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"10.5 MB"}
[2016-02-25 15:00:17] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/labels?page=1","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/labels?page=1","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/cotcot/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"13.5 MB"}
[2016-02-25 15:07:58] app.request.NOTICE: Route geo-places-get-all.fr matched [] {"url":"/api/v2/geo/places?embed=types,sources,country&page=1&sortBy=name:ASC","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/geo/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"11.25 MB"}
[2016-02-25 15:07:58] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/geo/places?embed=types%2Csources%2Ccountry&page=1&sortBy=name%3AASC","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/geo/places?embed=types,sources,country&page=1&sortBy=name:ASC","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/geo/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"14.25 MB"}
[2016-02-25 15:08:00] app.request.NOTICE: Route geo-places-get.fr matched [] {"url":"/api/v2/geo/places/3642?embed=types,sources,country,alternateCountries,geonames,aggregatedChildren","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/geo/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"11.25 MB"}
[2016-02-25 15:08:01] app.auth.INFO: entering authentication layer {"auth":"johann@evaneos.com","phpsessid":"tunkfmh3ka3l07tsdfpdbgh6v0","signature":"662e017350609748bd2614c49d799d53","ip":"172.17.0.13","method":"GET","uri":"http://pro.local.evaneos.com/api/v2/geo/places/3642?embed=types%2Csources%2Ccountry%2CalternateCountries%2Cgeonames%2CaggregatedChildren","ua":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"} {"url":"/api/v2/geo/places/3642?embed=types,sources,country,alternateCountries,geonames,aggregatedChildren","ip":"172.17.0.13","http_method":"GET","server":"pro.*","referrer":"http://pro.local.evaneos.com/geo/","tags":{"site_id":1,"locale":"fr","language_id":2,"user":"johann@evaneos.com"},"memory_usage":"14.25 MB"}
```

.... That give absolutely nothing to log inside a layer whereas we have a session stack to do that ...

**Comment by SelrahcD** [comment]
?

**Comment by remi-san** [comment]
Change your config to log only notice and up.

The more log we have, the more info we have to detect a bug or a pattern we could use.
Logs are good things. I think we don't have enough yet. So, please, don't delete the ones we have.

**Comment by SelrahcD** [comment]
> And it's not related to have everything in the same place, it's just logger config to do that. It's shitty log for nothing.

Did that log bothered you when it was not with all others ?

:D

**Comment by ProPheT777** [comment]
There are not value behind this log, it's just log to make log but it's useless. At least it's a DEBUG log but not production log. Log are a good things when you have a value behind. 

and 90% of data are useless

```
-                'phpsessid'     => $request->cookies->get(ini_get('session.name')),
 -                'signature'     => md5($request->headers->get('user-agent') . $request->getClientIp()),
 -                'ip'            => $request->getClientIp(),
 -                'method'        => $request->getMethod(),
 -                'uri'           => $request->getUri(),
 -                'ua'            => $request->headers->get('user-agent'),
```

Not related to the sec but to the incoming request.

Then the last 10% 

 ```
'auth' => $authentication->getPrincipal()
```

You got my email ... useless because your are logging in the layer whereas it should as log context populated when you retrieve the session nor the token header to rely all your log on the current connected user.

Now explain me in why it's useful to log that when you entered in this layer whereas it's can be done for every log?

**Comment by remi-san** [comment]
If the problem is that I don't capitalize on the data linked to this log call: yeah, you're right, they can be added to every log we make using processors. Please, feel free to do it, I'll be glad to validate a PR going that way.

I DO believe, nonetheless that this info is extremely important to give context.

Wanna lower the log declaration to debug, yeah, why not, it could be a point and I can live with that.

But no, I won't let you delete it without a fight.

**Comment by SelrahcD** [comment]
What we are saying is that we don't have that much logs and miss a lot of info. This log might not be as useful as it could be, but we disagree with your solution as other solution are possible - other file, debug, or raising log level if info are not useful (If I may having two separate files and two different log level is my preferred option).

> At least it's a DEBUG log but not production log. Log are a good things when you have a value behind.

I would argue that being able to debug shows that log has some value.

> Not related to the sec but to the incoming request.

Yup, their is possibly unnecessary data.

> You got my email ... useless because your are logging in the layer whereas it should as log context populated when you retrieve the session nor the token header to rely all your log on the current connected user.

Didn't get that part.

> Now explain me in why it's useful to log that when you entered in this layer whereas it's can be done for every log?

I'm starting to see your point is I guess. Are you trying to say that because we could add the info about the current user to every log we shouldn't log it by itself ?
Debatable. I might agree with you on this because the current log doesn't provide much more info than who is the current user but it would be different if the log were showing which authentication method was used for instance.

**Comment by ProPheT777** [comment]
> I'm starting to see your point is I guess. Are you trying to say that because we could add the info about the current user to every log we shouldn't log it by itself ?

Yes, It's already the case, until the user is logged in, the auth information is added to all log record

**Comment by SelrahcD** [comment]
> Yes, It's already the case, until the user is logged in, the auth information is added to all log record
:+1: on this

**Comment by ProPheT777** [comment]
https://github.com/Evaneos/pyrite/blob/master/src/KernelStack/LoggerMiddleware.php#L51

**Comment by SelrahcD** [comment]
https://gist.github.com/SelrahcD/f3a2b2475c90ebd684b5

**Pull request merged**
